name: Update GitHub Activity

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: 'sunjoe508'
          COMMIT_MSG: '⚡ Update recent GitHub activity'
          MAX_LINES: 10
